spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202304b
    username: postgres
    password:  postgres
server:
  servlet:
    context-path: /ec-202304b